name:  CI-CD-Piplanes-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "jooble-flask-aplication"
  EB_APPLICATION            : "Myflask"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha" }}.zip"
  AWS_REGION-NAME           : "eu-central-1"


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_ci_part:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    -name: Git clone our repo
    - uses: actions/checkout@v2
    
    - name: Create ZIP deployment packege
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
